name: 'Test and lint'
on: [ push ]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Test
        run: python -m unittest discover -s . -p 'test_*'
      - name: Lint
        run: pylint *.py --ignore-patterns=test --fail-under=9