name: 'Test and lint'
on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Test
        uses: onichandame/python-test-action@master
      - name: Lint
        uses: gabriel-milan/action-pylint@v1
        with:
          GITHUB_TOKEN: ${{secrets.WORKFLOW_TOKEN}} # GitHub token
          path: "./*.py" # Glob pattern for files to lint
          fail: false # Fail the action if pylint errors are found
          pr-message: true # Send a PR message if pylint errors are found
