name: 'Test and lint'
on: [push]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Test
        uses: onichandame/python-test-action@master
      - uses: actions/checkout@v2  
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "."
          mypy-options: "--ignore-missing-imports --show-error-codes"
          isort-options: "-w 100"
